### PR TITLE
Added all versions of Array templates

### PR DESCRIPTION
**Pull request by M-casado**
Actions taken:

- [ ] Moved all versions from their previous location in confluence (https://www.ebi.ac.uk/seqdb/confluence/display/EGA/EGA+AF+templates).
- [ ] Added a table with versions.
- [ ] Changed the CHANGELOG.md to reflect changes.

### CODE REVIEW

**Review by GiselleMarie — COMMENTED** [review]
LGTM @M-casado

**Comment by malloryfreeberg** [comment]
I have one suggestion:
- Change `all_versions/` to `old_versions` or `deprecated_versions`
- Remove the current version (4.3) from the `old_versions`/`deprecated_versions`

Justification: Better to not have v4.3 in two places and avoids suggesting that someone can use one of the older versions

**Review by malloryfreeberg — CHANGES_REQUESTED** [review]
I have one suggestion:
- Change `all_versions/` to `old_versions` or `deprecated_versions`
- Remove the current version (4.3) from the `old_versions`/`deprecated_versions`

Justification: Better to not have v4.3 in two places and avoids suggesting that someone can use one of the older versions

**Comment by M-casado** [comment]
> I have one suggestion:
> 
> * Change `all_versions/` to `old_versions` or `deprecated_versions`
> * Remove the current version (4.3) from the `old_versions`/`deprecated_versions`
> 
> Justification: Better to not have v4.3 in two places and avoids suggesting that someone can use one of the older versions

Sounds sensible, one sec.

**Review by malloryfreeberg — APPROVED** [review]
LGTM!

**Pull request merged**
