### PR TITLE
EE-2657_preview - Added drafted diagrams

### PR DESCRIPTION
**Pull request by M-casado**
## Ticket reference
EE-2657

## Overall changes
- Added drafted diagrams (poorly formatted for now) of both JSON schemas and JSON examples using PlantUML

## Future TO-DOs
- [x] Finish a Python script to streamline the whole diagram formatting and creation process
- [x] Replace the drafted diagrams with the finished ones.

### CODE REVIEW

**Review by Dona094 — COMMENTED** [review]
Awesome work.Have reviwed the readmd and reviewed some of the SVG files. 

I am getting at "Unable to render rich display Invalid image source" at
https://github.com/EbiEga/ega-metadata-schema/blob/EE-2657_preview/docs/json_diagrams/json_schemas/EGA.analysis.json/EGA.analysis_CVhighlights.svg 

I am not familiar with the code-base, but is the error at https://github.com/EbiEga/ega-metadata-schema/blob/EE-2657_preview/docs/json_diagrams/creating_schemas.ipynb expected?

Suggestions

In some SVG diagrams, the arrows pointing towards the ref seems to have overewritten the text. Would it be possible to shorten the arrow length so make the diagram more compact as in not overwriting over ref link? for eg at https://raw.githubusercontent.com/EbiEga/ega-metadata-schema/EE-2657_preview/docs/json_diagrams/json_documents/dataset/dataset_valid-1_whole.svg

**Comment by M-casado** [comment]
Good catch, @Dona094. The JSON files for both [``EGA.analysis_CVhighlights.svg``](https://github.com/EbiEga/ega-metadata-schema/blob/EE-2657_preview/docs/json_diagrams/json_schemas/EGA.analysis.json/EGA.analysis_CVhighlights.svg) and [``EGA.analysis_whole.svg``](https://github.com/EbiEga/ega-metadata-schema/blob/EE-2657_preview/docs/json_diagrams/json_schemas/EGA.analysis.json/EGA.analysis_whole.svg) do have content but their SVGs are empty. Other examples of empty SVGs are [``dataset_valid-1_ontologiesSubset.svg``](https://github.com/EbiEga/ega-metadata-schema/blob/EE-2657_preview/docs/json_diagrams/json_documents/dataset/dataset_valid-1_ontologiesSubset.svg), but in this case that is correct because the JSON file for this SVG, [``dataset_valid-1_ontologiesSubset.puml``](https://github.com/EbiEga/ega-metadata-schema/blob/EE-2657_preview/docs/json_diagrams/json_documents/dataset/puml_files/dataset_valid-1_ontologiesSubset.puml) is empty. There are 2 things I could improve for this matter:
- I will re-do the two wrong ones for the analysis.
- I could add a check in the script, so that if the JSON is completely empty, the files are not created. I didn't add it before because I wanted the format to be consistent, and not seeing any content in the graph, for me meant that there were no subsets and such. But the way an empty file is rendered in GitHub makes it look like there was a bug or something, so I may add this check and if there's not a file, it's simply because it had no content.


Regarding the [error](https://github.com/EbiEga/ega-metadata-schema/blob/EE-2657_preview/docs/json_diagrams/creating_schemas.ipynb) you mentioned: I also found that PlantUML gave some warnings that did not affect the output. So I most likely didn't pay attention to these. It's been some time, but I believe it wasn't an error per se, but probably that PlantUML found an empty JSON and couldn't render it. Perhaps these warnings get solved with the previous check.


> Would it be possible to shorten the arrow length so make the diagram more compact as in not overwriting over ref link? 
This may be more complex, given the little freedom for now in modifying the format of the graphs that are transformed into SVG. There are other issues, like arrows coming out of properties that are not the correct one because the text is too big and things like that. I plan to:
- Create an issue at [their repo](https://github.com/plantuml/plantuml/issues?q=is%3Aissue+is%3Aopen+arrows) to request a fix of these incorrect arrows.
- Create an issue at [their repo](https://github.com/plantuml/plantuml/issues?q=is%3Aissue+is%3Aopen+arrows) for them to not super-impose the arrows onto the text.

**Comment by M-casado** [comment]
Created GH issue for plantUML to fix the arrows: https://github.com/plantuml/plantuml/issues/1334

**Comment by M-casado** [comment]
And... accidentally closed it when commenting... Merging now.

**Pull request merged**
