### PR TITLE
EE-2363 - Updated metadata diagrams

### PR DESCRIPTION
**Pull request by M-casado**
- [ ] Added simplistic diagram
- [ ] Added entity-like diagram with differences
- [ ] Added context in the README

### CODE REVIEW

**Review by Dona094 — COMMENTED** [review]
The first diagram looks good to me. I would like to provide some suggestions/feedback for the second diagram pls.

A little more context on what the + sign is referring to (maybe using a legend or even a text in the readme doc) as it can be confusing for the user if the ‘+’ sign is referring to the mandatory attributes or the if it is referring to some of the major attributes of the EGA object in question.

Dataset - Compilation of owned datafiles. I was wondering if the Compilation or collection of data files with a common data access policy describes better?

Referring to some typos in the second diagram
DAC
Data controlers should be Data controllers
Dataset
Aprox. release date should be Approx. release date

**Comment by M-casado** [comment]
hi @Dona094, thank you for your feedback.

> A little more context on what the + sign is referring to (maybe using a legend or even a text in the readme doc)...

What I had in mind is what is right above the second diagram. Perhaps is not clear that it refers to the "+" symbol. I'll add it between parentheses. 
> Besides these common fields, each has their own bespoken attributes, visible in the following entity diagram:

> Dataset - Compilation of owned datafiles. I was wondering if the Compilation or collection of data files with a common data access policy describes better?

My idea was initially to have ``Compilation of uniformly owned datafiles``, but it was a bit long to add in the diagram, so your definition, while way more accurate is also a bit long for a summary diagram 🤔 I'll see what I can do and ask for your feedback again. 

> Referring to some typos in the second diagram

Yep, completely missed those. Thank you!

**Comment by Dona094** [comment]
Hi @M-casado 

Thank you very much for incorporating the suggestions. Could I please check two things with you? 

1. Should it be a compilation of datafiles under the same policy? Are we missing the word 'of'?
2. I was wondering if it is possible to add a space between the second diagram and the sentence above it as it seems a bit too close to each other at a glance

**Review by Dona094 — APPROVED** [review]
Looks great to me!! Awesome job

**Pull request merged**
